import {User} from "./user";

export const USERS : User[] =[
    {
        id: "User1",
        firstName: "One",
        lastName: "User",
        age: 22,
        login: "",
        password: "",
        isDeleted: true,
      },
      {
        id: "User2",
        firstName: "Two",
        lastName: "User",
        age: 23,
        login: "",
        password: "",
        isDeleted: false,
      },
      {
        id: "User3",
        firstName: "Three",
        lastName: "User",
        age: 24,
        login: "",
        password: "",
        isDeleted: true,
      },
      {
        id: "User4",
        firstName: "Four",
        lastName: "User",
        age: 25,
        login: "",
        password: "",
        isDeleted: false,
      },
      {
        id: "User5",
        firstName: "Five",
        lastName: "User",
        age: 26,
        login: "",
        password: "",
        isDeleted: false,
      },
      {
        id: "User6",
        firstName: "Six",
        lastName: "User",
        age: 27,
        login: "",
        password: "",
        isDeleted: false,
      },
      {
        id: "User7",
        firstName: "Seven",
        lastName: "User",
        age: 28,
        login: "",
        password: "",
        isDeleted: true,
      },
      {
        id: "User8",
        firstName: "Eight",
        lastName: "User",
        age: 29,
        login: "",
        password: "",
        isDeleted: true,
      }
]